create table
  public.cart_items (
    item_id integer generated by default as identity,
    potion_id integer not null default 0,
    quantity integer not null default 0,
    cart_id integer not null default 0,
    constraint cart_items_pkey primary key (item_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potions (potion_id)
  ) tablespace pg_default;

  create table
  public.carts (
    cart_id integer generated by default as identity,
    customer_name text not null default 'string'::text,
    total_cost integer not null default 0,
    total_potion_num integer not null default 0,
    constraint carts_pkey primary key (cart_id)
  ) tablespace pg_default;

  create table
  public.global_inventory (
    num_red_ml integer not null default 0,
    gold integer not null default 100,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    shop integer not null default 1,
    num_dark_ml integer not null default 0,
    constraint global_inventory_pkey primary key (shop)
  ) tablespace pg_default;

  create table
  public.potions (
    potion_id integer generated by default as identity,
    sku text not null default 'string'::text,
    name text not null default 'string'::text,
    price integer not null default 0,
    quantity integer not null default 0,
    red_ml integer not null default 0,
    green_ml integer not null default 0,
    blue_ml integer not null default 0,
    dark_ml integer not null default 0,
    constraint potions_pkey primary key (potion_id)
  ) tablespace pg_default;

