create table
  public.cart_items (
    item_id integer generated by default as identity,
    potion_id integer not null default 0,
    quantity integer not null default 0,
    cart_id integer not null default 0,
    constraint cart_items_pkey primary key (item_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id)
  ) tablespace pg_default;

  create table
  public.carts (
    cart_id integer generated by default as identity,
    customer_name text not null default 'string'::text,
    constraint carts_pkey primary key (cart_id)
  ) tablespace pg_default;

  create table
  public.gold_ledger (
    ledger_id integer generated by default as identity,
    gold integer not null default 0,
    transaction_id integer null,
    constraint gold_ledger_pkey primary key (ledger_id),
    constraint gold_ledger_transaction_id_fkey foreign key (transaction_id) references transaction (transaction_id)
  ) tablespace pg_default;

  create table
  public.ml_ledger (
    ledger_id integer generated by default as identity,
    transaction_id integer not null,
    red_ml integer null default 0,
    green_ml integer null default 0,
    blue_ml integer null default 0,
    dark_ml integer null default 0,
    constraint shop_ledger_pkey primary key (ledger_id)
  ) tablespace pg_default;

  create table
  public.potion_ledger (
    ledger_id integer generated by default as identity,
    transaction_id integer not null,
    potion_id integer null,
    quantity integer null default 0,
    constraint potion_ledger_pkey primary key (ledger_id),
    constraint potion_ledger_transaction_id_fkey foreign key (transaction_id) references transaction (transaction_id)
  ) tablespace pg_default;

  create table
  public.transaction (
    transaction_id integer generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text null default 'string'::text,
    constraint transaction_pkey primary key (transaction_id)
  ) tablespace pg_default;
